In [16]:
from keras.datasets import imdb
from sklearn.metrics import confusion_matrix
import numpy as np

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [2]:
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?')
                          for i in train_data[2]])

In [3]:
decoded_review

"? this has to be one of the worst films of the 1990s when my friends i were watching this film being the target audience it was aimed at we just sat watched the first half an hour with our jaws touching the floor at how bad it really was the rest of the time everyone else in the theatre just started talking to each other leaving or generally crying into their popcorn that they actually paid money they had ? working to watch this feeble excuse for a film it must have looked like a great idea on paper but on film it looks like no one in the film has a clue what is going on crap acting crap costumes i can't get across how ? this is to watch save yourself an hour a bit of your life"

In [4]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results
X_train  = vectorize_sequences(train_data)
X_test = vectorize_sequences(test_data)

In [5]:
X_train[2]

array([0., 1., 1., ..., 0., 0., 0.])

In [6]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [10]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape = (10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [11]:
X_val = X_train[:10000]
partial_X_train = X_train[10000:]
y_val = y_train[:10000]
partial_y_train = y_train[10000:]

In [13]:
model.fit(partial_X_train,
          partial_y_train,
          epochs=40,
          batch_size=512,
          validation_data=(X_val,y_val))

Epoch 1/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.9999 - loss: 0.0068 - val_accuracy: 0.8544 - val_loss: 0.6741
Epoch 2/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9996 - loss: 0.0077 - val_accuracy: 0.8692 - val_loss: 0.6246
Epoch 3/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9993 - loss: 0.0072 - val_accuracy: 0.8709 - val_loss: 0.6319
Epoch 4/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9999 - loss: 0.0038 - val_accuracy: 0.8708 - val_loss: 0.6496
Epoch 5/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9990 - loss: 0.0062 - val_accuracy: 0.8710 - val_loss: 0.6659
Epoch 6/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9998 - loss: 0.0031 - val_accuracy: 0.8680 - val_loss: 0.6934
Epoch 7/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9979 - loss: 0.0082 - val_accuracy: 0.8694 - val_loss: 0.6993
Epoch 8/40
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.8700 - v

In [14]:
model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([[2.7180118e-05],
       [1.0000000e+00],
       [6.6332072e-02],
       ...,
       [8.3976585e-07],
       [4.4365875e-06],
       [9.7232008e-01]], dtype=float32)

In [15]:
model.evaluate(X_test, y_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8518 - loss: 1.3021


[1.2774839401245117, 0.8557199835777283]

In [17]:
predictions = model.predict(X_test)
binary_predictions = (predictions > 0.5).astype('int')
conf_matrix = confusion_matrix(y_test, binary_predictions)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [19]:
print(conf_matrix)

[[10837  1663]
 [ 1944 10556]]
